version: '3'

services:
  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - ./database_postgresql/database.env # configure postgres
    volumes:
      - ./database_postgresql/customPostgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./database_postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql # persist data even if container shuts down
      - database-data:/var/lib/postgresql/data/
    ports:
      - 5436:5432
    
    networks:
        node_net:
          ipv4_address: 172.28.1.4
  fruits-service:
    build: ./fruits
    volumes:
     - ./fruits:/usr/src/app
    ports:
     - 5001:80
  website:
    image: php:apache
    volumes:
     - ./web:/var/www/html
    ports:
     - 5000:80
    depends_on:
     - fruits-service
  
volumes:
  database-data:



networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16