version: '3'

services:
  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - ./database_postgresql/database.env # configurando postgres
    volumes:
      - ./database_postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql # persistir la informacion
      - database-data:/var/lib/postgresql/data/
    expose:
      - 5432
    networks:
      - app-tier
    
    
  fruits-service:
    restart: always
    build: ./fruits
    volumes:
     - ./fruits:/usr/src/app
    ports:
     - 5001:80
    depends_on: 
     - database
    networks:
     - app-tier

  website:
    image: php:apache
    volumes:
     - ./web:/var/www/html
    ports:
     - 5000:80
    depends_on:
     - fruits-service
    networks:
     - app-tier

networks:
  app-tier:
    driver: bridge     
volumes:
  database-data:

