version: '3'

services:
  fruits-service:
    build: ./fruits
    volumes:
     - ./fruits:/usr/src/app
    ports:
     - 5001:80
  website:
    image: php:apache
    volumes:
     - ./web:/var/www/html
    ports:
     - 5000:80
    depends_on:
     - fruits-service
